version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Submodule Update: "
    reviewers:
      - "fedora-iot/iot-team"
